// src/services/sampleData.ts
import type { Person } from '../types';

export const samplePeople: Person[] = [
  // ───────────── Generation 1 ─────────────
  {
    id: 'p001',
    name: 'Karl Geppert',
    code: '1',
    ringCode: '1',
    parentId: null,
    partnerId: 'p002',
    gender: 'm',
    hasRing: true,
    birthDate: '1930-04-15',
    birthPlace: 'Berlin',
    deathDate: '1995-03-10',
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Stammvater der Linie; Handwerksmeister.',
  },
  {
    id: 'p002',
    name: 'Anna Müller-Geppert',
    code: '1x',
    ringCode: '1x',
    parentId: null,
    partnerId: 'p001',
    gender: 'w',
    hasRing: false,
    birthDate: '1932-06-20',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Ehefrau von Karl; geb. Müller.',
  },

  // ───────────── Generation 2 ─────────────
  {
    id: 'p003',
    name: 'Hans Geppert',
    code: '1A',
    ringCode: '1 → 1A',
    parentId: 'p001',
    partnerId: 'p004',
    gender: 'm',
    hasRing: true,
    birthDate: '1955-02-12',
    birthPlace: 'Berlin',
    deathDate: '2021-04-05',
    photoUrl: null,
    inheritedFrom: 'p001',
    comment: 'Ältester Sohn; übernahm den Ring von Karl.',
  },
  {
    id: 'p004',
    name: 'Maria Schulze-Geppert',
    code: '1Ax',
    ringCode: '1Ax',
    parentId: null,
    partnerId: 'p003',
    gender: 'w',
    hasRing: true,
    birthDate: '1956-09-10',
    birthPlace: 'Hamburg',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Ehefrau von Hans; Lehrerin.',
  },

  {
    id: 'p005',
    name: 'Peter Geppert',
    code: '1B',
    ringCode: '1B',
    parentId: 'p001',
    partnerId: 'p006',
    gender: 'm',
    hasRing: true,
    birthDate: '1958-07-01',
    birthPlace: 'Berlin',
    deathDate: '2018-02-15',
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Zweiter Sohn; leidenschaftlicher Gärtner.',
  },
  {
    id: 'p006',
    name: 'Sabine Krüger-Geppert',
    code: '1Bx',
    ringCode: '1Bx',
    parentId: null,
    partnerId: 'p005',
    gender: 'w',
    hasRing: false,
    birthDate: '1960-01-22',
    birthPlace: 'Köln',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Ehefrau von Peter; Krankenschwester.',
  },

  {
    id: 'p007',
    name: 'Clara Geppert',
    code: '1C',
    ringCode: '1C',
    parentId: 'p001',
    partnerId: 'p008',
    gender: 'w',
    hasRing: true,
    birthDate: '1961-03-14',
    birthPlace: 'Berlin',
    deathDate: '2020-11-20',
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Tochter; Architekturzeichnerin.',
  },
  {
    id: 'p008',
    name: 'Markus Schneider-Geppert',
    code: '1Cx',
    ringCode: '1Cx',
    parentId: null,
    partnerId: 'p007',
    gender: 'm',
    hasRing: true,
    birthDate: '1959-11-03',
    birthPlace: 'Stuttgart',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Ehemann von Clara; Ingenieur.',
  },

  {
    id: 'p009',
    name: 'Otto Geppert',
    code: '1D',
    ringCode: '1D',
    parentId: 'p001',
    partnerId: 'p010',
    gender: 'm',
    hasRing: true,
    birthDate: '1963-05-22',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Jüngster Sohn; Buchhändler.',
  },
  {
    id: 'p010',
    name: 'Julia Weber-Geppert',
    code: '1Dx',
    ringCode: '1Dx',
    parentId: null,
    partnerId: 'p009',
    gender: 'w',
    hasRing: false,
    birthDate: '1965-12-05',
    birthPlace: 'Leipzig',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Ehefrau von Otto; Museumspädagogin.',
  },

  // ───────────── Generation 3 ─────────────
  {
    id: 'p011',
    name: 'Anna Geppert',
    code: '1A1',
    ringCode: '1 → 1A → 1A1',
    parentId: 'p003',
    partnerId: null,
    gender: 'w',
    hasRing: true,
    birthDate: '1979-04-09',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: 'p003',
    comment: 'Tochter von Hans; erbte nach seinem Tod.',
  },
  {
    id: 'p012',
    name: 'Bernd Geppert',
    code: '1A2',
    ringCode: '1A2',
    parentId: 'p003',
    partnerId: null,
    gender: 'm',
    hasRing: true,
    birthDate: '1982-01-28',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Zweiter Nachwuchs von Hans.',
  },
  {
    id: 'p013',
    name: 'Thomas Geppert',
    code: '1B1',
    ringCode: '1B → 1B1',
    parentId: 'p005',
    partnerId: 'p014',
    gender: 'm',
    hasRing: true,
    birthDate: '1985-07-19',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: 'p005',
    comment: 'Sohn von Peter; erbte nach dessen Tod.',
  },
  {
    id: 'p014',
    name: 'Katrin Hoffmann-Geppert',
    code: '1B1x',
    ringCode: '1B1x',
    parentId: null,
    partnerId: 'p013',
    gender: 'w',
    hasRing: true,
    birthDate: '1987-02-11',
    birthPlace: 'Hannover',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Ehefrau von Thomas; Ärztin.',
  },

  {
    id: 'p015',
    name: 'Julia Geppert',
    code: '1C1',
    ringCode: '1C → 1C1',
    parentId: 'p007',
    partnerId: 'p016',
    gender: 'w',
    hasRing: true,
    birthDate: '1984-08-03',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: 'p007',
    comment: 'Tochter von Clara.',
  },
  {
    id: 'p016',
    name: 'David König-Geppert',
    code: '1C1x',
    ringCode: '1C1x',
    parentId: null,
    partnerId: 'p015',
    gender: 'm',
    hasRing: true,
    birthDate: '1982-12-21',
    birthPlace: 'München',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Ehemann von Julia; Informatiker.',
  },

  {
    id: 'p017',
    name: 'Michael Geppert',
    code: '1C2',
    ringCode: '1C2',
    parentId: 'p007',
    partnerId: 'p018',
    gender: 'm',
    hasRing: true,
    birthDate: '1987-11-15',
    birthPlace: 'Berlin',
    deathDate: '2022-09-09',
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Sohn von Clara; Musiker.',
  },
  {
    id: 'p018',
    name: 'Laura Meier-Geppert',
    code: '1C2x',
    ringCode: '1C2x',
    parentId: null,
    partnerId: 'p017',
    gender: 'w',
    hasRing: true,
    birthDate: '1989-03-08',
    birthPlace: 'Hamburg',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Ehefrau von Michael.',
  },

  {
    id: 'p019',
    name: 'Lena Geppert',
    code: '1D1',
    ringCode: '1D1',
    parentId: 'p009',
    partnerId: 'p020',
    gender: 'w',
    hasRing: true,
    birthDate: '1990-02-02',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Tochter von Otto.',
  },
  {
    id: 'p020',
    name: 'Andreas Braun-Geppert',
    code: '1D1x',
    ringCode: '1D1x',
    parentId: null,
    partnerId: 'p019',
    gender: 'm',
    hasRing: false,
    birthDate: '1988-05-17',
    birthPlace: 'Bonn',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Ehemann von Lena.',
  },

  {
    id: 'p021',
    name: 'Jonas Geppert',
    code: '1D2',
    ringCode: '1D2',
    parentId: 'p009',
    partnerId: 'p022',
    gender: 'm',
    hasRing: true,
    birthDate: '1992-10-01',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Sohn von Otto.',
  },
  {
    id: 'p022',
    name: 'Miriam Vogel-Geppert',
    code: '1D2x',
    ringCode: '1D2x',
    parentId: null,
    partnerId: 'p021',
    gender: 'w',
    hasRing: true,
    birthDate: '1994-01-29',
    birthPlace: 'Dresden',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Ehefrau von Jonas.',
  },

  {
    id: 'p023',
    name: 'Sarah Geppert',
    code: '1D3',
    ringCode: '1D3',
    parentId: 'p009',
    partnerId: 'p024',
    gender: 'w',
    hasRing: true,
    birthDate: '1994-06-13',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Jüngste Tochter von Otto.',
  },
  {
    id: 'p024',
    name: 'Felix Richter-Geppert',
    code: '1D3x',
    ringCode: '1D3x',
    parentId: null,
    partnerId: 'p023',
    gender: 'm',
    hasRing: false,
    birthDate: '1993-07-27',
    birthPlace: 'Mainz',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Ehemann von Sarah.',
  },

  // ───────────── Generation 4 ─────────────
  {
    id: 'p025',
    name: 'Nico Geppert',
    code: '1B11',
    ringCode: '1B11',
    parentId: 'p013',
    partnerId: null,
    gender: 'm',
    hasRing: true,
    birthDate: '2012-04-11',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Sohn von Thomas und Katrin.',
  },
  {
    id: 'p026',
    name: 'Mia Geppert',
    code: '1C11',
    ringCode: '1C11',
    parentId: 'p015',
    partnerId: null,
    gender: 'w',
    hasRing: true,
    birthDate: '2010-08-22',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Tochter von Julia und David.',
  },
  {
    id: 'p027',
    name: 'Lukas Geppert',
    code: '1C21',
    ringCode: '1C21',
    parentId: 'p017',
    partnerId: null,
    gender: 'm',
    hasRing: true,
    birthDate: '2014-01-10',
    birthPlace: 'Hamburg',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Sohn von Michael und Laura.',
  },
  {
    id: 'p028',
    name: 'Lea Geppert',
    code: '1D11',
    ringCode: '1D11',
    parentId: 'p019',
    partnerId: null,
    gender: 'w',
    hasRing: false,
    birthDate: '2016-05-06',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Tochter von Lena und Andreas.',
  },
  {
    id: 'p029',
    name: 'Paul Geppert',
    code: '1D21',
    ringCode: '1D21',
    parentId: 'p021',
    partnerId: null,
    gender: 'm',
    hasRing: true,
    birthDate: '2018-03-18',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Sohn von Jonas und Miriam.',
  },
  {
    id: 'p030',
    name: 'Sophie Geppert',
    code: '1D31',
    ringCode: '1D31',
    parentId: 'p023',
    partnerId: null,
    gender: 'w',
    hasRing: true,
    birthDate: '2020-09-12',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Tochter von Sarah und Felix.',
  },

  // ───────────── Generation 5 ─────────────
  {
    id: 'p031',
    name: 'Emilia Geppert',
    code: '1C211',
    ringCode: '1C211',
    parentId: 'p027',
    partnerId: null,
    gender: 'w',
    hasRing: true,
    birthDate: '2023-01-01',
    birthPlace: 'Hamburg',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: 'p017',
    comment: 'Enkelin von Michael; erbte Ring nach dessen Tod.',
  },
  {
    id: 'p032',
    name: 'Finn Geppert',
    code: '1D211',
    ringCode: '1D211',
    parentId: 'p029',
    partnerId: null,
    gender: 'm',
    hasRing: true,
    birthDate: '2024-05-09',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Urenkel von Otto.',
  },
  {
    id: 'p033',
    name: 'Ella Geppert',
    code: '1D311',
    ringCode: '1D311',
    parentId: 'p030',
    partnerId: null,
    gender: 'w',
    hasRing: false,
    birthDate: '2024-07-17',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Tochter von Sophie; kein Ring.',
  },
  {
    id: 'p034',
    name: 'Noah Geppert',
    code: '1B111',
    ringCode: '1B111',
    parentId: 'p025',
    partnerId: null,
    gender: 'm',
    hasRing: true,
    birthDate: '2024-02-28',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Urenkel von Thomas; trägt Ring fort.',
  },
  {
    id: 'p035',
    name: 'Clara Geppert',
    code: '1C111',
    ringCode: '1C111',
    parentId: 'p026',
    partnerId: null,
    gender: 'w',
    hasRing: true,
    birthDate: '2025-01-15',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Jüngste im Stammbaum (Generation 5).',
  },
];

export default samplePeople;

    
