// src/services/sampleData.ts
import { Person } from '../types';

/**
 * KORRIGIERTE BEISPIELDATEN
 * - inheritedFrom enthält jetzt immer den PERSONEN-CODE des Erblassers (nicht die ID)
 * - Partner-Codes enden konsistent mit 'x' und sind wechselseitig verlinkt
 * - parentId verweist bei Kindern auf den nicht-Partner-Elternteil (den ohne 'x')
 * - hasRing/ringCode bilden eine saubere Vererbungskette (1 → 1A → 1A1 → 1A11)
 */

const sampleData: Person[] = [
  // Generation 1 (Stamm)
  {
    id: 'p1',
    code: '1',
    name: 'Adam Geppert',
    gender: 'm',
    birthDate: '1940-02-12',
    deathDate: null,
    birthPlace: 'Leipzig',
    parentId: null,
    partnerId: 'p2',
    hasRing: true,
    ringCode: '1',
    ringHistory: [],
    inheritedFrom: null,
    comment: null,
    photoUrl: null,
  },
  {
    id: 'p2',
    code: '1x',
    name: 'Eva Geppert',
    gender: 'f',
    birthDate: '1942-06-21',
    deathDate: null,
    birthPlace: 'Dresden',
    parentId: null,
    partnerId: 'p1',
    hasRing: false,
    ringCode: '1x',
    ringHistory: [],
    inheritedFrom: null,
    comment: null,
    photoUrl: null,
  },

  // Generation 2 (Kinder von 1)
  {
    id: 'p3',
    code: '1A',
    name: 'Bernd Geppert',
    gender: 'm',
    birthDate: '1965-05-08',
    deathDate: null,
    birthPlace: 'Berlin',
    parentId: 'p1',
    partnerId: 'p4',
    hasRing: true,
    ringCode: '1 → 1A',
    ringHistory: [],
    inheritedFrom: '1',
    comment: null,
    photoUrl: null,
  },
  {
    id: 'p4',
    code: '1Ax',
    name: 'Claudia Geppert',
    gender: 'f',
    birthDate: '1966-04-10',
    deathDate: null,
    birthPlace: 'Berlin',
    parentId: null,
    partnerId: 'p3',
    hasRing: false,
    ringCode: '1Ax',
    ringHistory: [],
    inheritedFrom: null,
    comment: null,
    photoUrl: null,
  },
  {
    id: 'p5',
    code: '1B',
    name: 'Doris Geppert',
    gender: 'f',
    birthDate: '1967-03-17',
    deathDate: null,
    birthPlace: 'Hamburg',
    parentId: 'p1',
    partnerId: 'p6',
    hasRing: false,
    ringCode: '1B',
    ringHistory: [],
    inheritedFrom: null,
    comment: null,
    photoUrl: null,
  },
  {
    id: 'p6',
    code: '1Bx',
    name: 'Erik Geppert',
    gender: 'm',
    birthDate: '1965-10-28',
    deathDate: null,
    birthPlace: 'Hamburg',
    parentId: null,
    partnerId: 'p5',
    hasRing: false,
    ringCode: '1Bx',
    ringHistory: [],
    inheritedFrom: null,
    comment: null,
    photoUrl: null,
  },
  {
    id: 'p7',
    code: '1C',
    name: 'Friedrich Geppert',
    gender: 'm',
    birthDate: '1970-11-02',
    deathDate: null,
    birthPlace: 'München',
    parentId: 'p1',
    partnerId: 'p8',
    hasRing: false,
    ringCode: '1C',
    ringHistory: [],
    inheritedFrom: null,
    comment: null,
    photoUrl: null,
  },
  {
    id: 'p8',
    code: '1Cx',
    name: 'Gabriele Geppert',
    gender: 'f',
    birthDate: '1972-09-05',
    deathDate: null,
    birthPlace: 'München',
    parentId: null,
    partnerId: 'p7',
    hasRing: false,
    ringCode: '1Cx',
    ringHistory: [],
    inheritedFrom: null,
    comment: null,
    photoUrl: null,
  },
  {
    id: 'p27',
    code: '1D',
    name: 'Helmut Geppert',
    gender: 'm',
    birthDate: '1973-07-07',
    deathDate: null,
    birthPlace: 'Köln',
    parentId: 'p1',
    partnerId: 'p28',
    hasRing: false,
    ringCode: '1D',
    ringHistory: [],
    inheritedFrom: null,
    comment: null,
    photoUrl: null,
  },
  {
    id: 'p28',
    code: '1Dx',
    name: 'Iris Geppert',
    gender: 'f',
    birthDate: '1975-03-03',
    deathDate: null,
    birthPlace: 'Köln',
    parentId: null,
    partnerId: 'p27',
    hasRing: false,
    ringCode: '1Dx',
    ringHistory: [],
    inheritedFrom: null,
    comment: null,
    photoUrl: null,
  },

  // Generation 3
  // Kinder von 1A (p3)
  {
    id: 'p9',
    code: '1A1',
    name: 'Jakob Geppert',
    gender: 'm',
    birthDate: '1990-01-14',
    deathDate: null,
    birthPlace: 'Berlin',
    parentId: 'p3',
    partnerId: 'p10',
    hasRing: true,
    ringCode: '1 → 1A → 1A1',
    ringHistory: [],
    inheritedFrom: '1A',
    comment: null,
    photoUrl: null,
  },
  {
    id: 'p10',
    code: '1A1x',
    name: 'Katharina Geppert',
    gender: 'f',
    birthDate: '1991-07-22',
    deathDate: null,
    birthPlace: 'Berlin',
    parentId: null,
    partnerId: 'p9',
    hasRing: false,
    ringCode: '1A1x',
    ringHistory: [],
    inheritedFrom: null,
    comment: null,
    photoUrl: null,
  },
  {
    id: 'p11',
    code: '1A2',
    name: 'Lena Geppert',
    gender: 'f',
    birthDate: '1992-12-03',
    deathDate: null,
    birthPlace: 'Berlin',
    parentId: 'p3',
    partnerId: 'p12',
    hasRing: false,
    ringCode: '1A2',
    ringHistory: [],
    inheritedFrom: null,
    comment: null,
    photoUrl: null,
  },
  {
    id: 'p12',
    code: '1A2x',
    name: 'Martin Geppert',
    gender: 'm',
    birthDate: '1990-03-29',
    deathDate: null,
    birthPlace: 'Potsdam',
    parentId: null,
    partnerId: 'p11',
    hasRing: false,
    ringCode: '1A2x',
    ringHistory: [],
    inheritedFrom: null,
    comment: null,
    photoUrl: null,
  },

  // Kinder von 1B (p5)
  {
    id: 'p13',
    code: '1B1',
    name: 'Nora Geppert',
    gender: 'f',
    birthDate: '1989-08-09',
    deathDate: null,
    birthPlace: 'Hamburg',
    parentId: 'p5',
    partnerId: 'p14',
    hasRing: false,
    ringCode: '1B1',
    ringHistory: [],
    inheritedFrom: null,
    comment: null,
    photoUrl: null,
  },
  {
    id: 'p14',
    code: '1B1x',
    name: 'Oliver Geppert',
    gender: 'm',
    birthDate: '1991-01-30',
    deathDate: null,
    birthPlace: 'Hamburg',
    parentId: null,
    partnerId: 'p13',
    hasRing: false,
    ringCode: '1B1x',
    ringHistory: [],
    inheritedFrom: null,
    comment: null,
    photoUrl: null,
  },
  {
    id: 'p15',
    code: '1B2',
    name: 'Paul Geppert',
    gender: 'm',
    birthDate: '1994-02-14',
    deathDate: null,
    birthPlace: 'Hamburg',
    parentId: 'p5',
    partnerId: 'p16',
    hasRing: false,
    ringCode: '1B2',
    ringHistory: [],
    inheritedFrom: null,
    comment: null,
    photoUrl: null,
  },
  {
    id: 'p16',
    code: '1B2x',
    name: 'Queena Geppert',
    gender: 'f',
    birthDate: '1995-06-01',
    deathDate: null,
    birthPlace: 'Hamburg',
    parentId: null,
    partnerId: 'p15',
    hasRing: false,
    ringCode: '1B2x',
    ringHistory: [],
    inheritedFrom: null,
    comment: null,
    photoUrl: null,
  },

  // Kinder von 1C (p7)
  {
    id: 'p17',
    code: '1C1',
    name: 'Ruth Geppert',
    gender: 'f',
    birthDate: '1998-05-25',
    deathDate: null,
    birthPlace: 'München',
    parentId: 'p7',
    partnerId: 'p18',
    hasRing: false,
    ringCode: '1C1',
    ringHistory: [],
    inheritedFrom: null,
    comment: null,
    photoUrl: null,
  },
  {
    id: 'p18',
    code: '1C1x',
    name: 'Stefan Geppert',
    gender: 'm',
    birthDate: '1997-09-09',
    deathDate: null,
    birthPlace: 'München',
    parentId: null,
    partnerId: 'p17',
    hasRing: false,
    ringCode: '1C1x',
    ringHistory: [],
    inheritedFrom: null,
    comment: null,
    photoUrl: null,
  },

  // Generation 4
  // Kinder von 1A1 (p9)
  {
    id: 'p19',
    code: '1A11',
    name: 'Tim Geppert',
    gender: 'm',
    birthDate: '2015-03-03',
    deathDate: null,
    birthPlace: 'Berlin',
    parentId: 'p9',
    partnerId: 'p20',
    hasRing: true,
    ringCode: '1 → 1A → 1A1 → 1A11',
    ringHistory: [],
    inheritedFrom: '1A1',
    comment: null,
    photoUrl: null,
  },
  {
    id: 'p20',
    code: '1A11x',
    name: 'Ulrike Geppert',
    gender: 'f',
    birthDate: '2016-07-07',
    deathDate: null,
    birthPlace: 'Berlin',
    parentId: null,
    partnerId: 'p19',
    hasRing: false,
    ringCode: '1A11x',
    ringHistory: [],
    inheritedFrom: null,
    comment: null,
    photoUrl: null,
  },
  {
    id: 'p21',
    code: '1A12',
    name: 'Vera Geppert',
    gender: 'f',
    birthDate: '2018-10-11',
    deathDate: null,
    birthPlace: 'Berlin',
    parentId: 'p9',
    partnerId: null,
    hasRing: false,
    ringCode: '1A12',
    ringHistory: [],
    inheritedFrom: null,
    comment: null,
    photoUrl: null,
  },

  // Kinder von 1A2 (p11)
  {
    id: 'p22',
    code: '1A21',
    name: 'Willi Geppert',
    gender: 'm',
    birthDate: '2013-01-02',
    deathDate: null,
    birthPlace: 'Berlin',
    parentId: 'p11',
    partnerId: null,
    hasRing: false,
    ringCode: '1A21',
    ringHistory: [],
    inheritedFrom: null,
    comment: null,
    photoUrl: null,
  },

  // Kinder von 1B1 (p13)
  {
    id: 'p23',
    code: '1B11',
    name: 'Xenia Geppert',
    gender: 'f',
    birthDate: '2012-05-16',
    deathDate: null,
    birthPlace: 'Hamburg',
    parentId: 'p13',
    partnerId: null,
    hasRing: false,
    ringCode: '1B11',
    ringHistory: [],
    inheritedFrom: null,
    comment: null,
    photoUrl: null,
  },

  // Kinder von 1B2 (p15)
  {
    id: 'p24',
    code: '1B21',
    name: 'Yannic Geppert',
    gender: 'm',
    birthDate: '2019-09-23',
    deathDate: null,
    birthPlace: 'Hamburg',
    parentId: 'p15',
    partnerId: null,
    hasRing: false,
    ringCode: '1B21',
    ringHistory: [],
    inheritedFrom: null,
    comment: null,
    photoUrl: null,
  },
  {
    id: 'p25',
    code: '1B22',
    name: 'Zoe Geppert',
    gender: 'f',
    birthDate: '2021-12-01',
    deathDate: null,
    birthPlace: 'Hamburg',
    parentId: 'p15',
    partnerId: null,
    hasRing: false,
    ringCode: '1B22',
    ringHistory: [],
    inheritedFrom: null,
    comment: null,
    photoUrl: null,
  },

  // Kinder von 1C1 (p17)
  {
    id: 'p26',
    code: '1C11',
    name: 'Aaron Geppert',
    gender: 'm',
    birthDate: '2020-04-04',
    deathDate: null,
    birthPlace: 'München',
    parentId: 'p17',
    partnerId: null,
    hasRing: false,
    ringCode: '1C11',
    ringHistory: [],
    inheritedFrom: null,
    comment: null,
    photoUrl: null,
  },

  // Kinder von 1D (p27)
  {
    id: 'p29',
    code: '1D1',
    name: 'Britta Geppert',
    gender: 'f',
    birthDate: '2000-08-08',
    deathDate: null,
    birthPlace: 'Köln',
    parentId: 'p27',
    partnerId: 'p30',
    hasRing: false,
    ringCode: '1D1',
    ringHistory: [],
    inheritedFrom: null,
    comment: null,
    photoUrl: null,
  },
  {
    id: 'p30',
    code: '1D1x',
    name: 'Carsten Geppert',
    gender: 'm',
    birthDate: '1998-02-02',
    deathDate: null,
    birthPlace: 'Köln',
    parentId: null,
    partnerId: 'p29',
    hasRing: false,
    ringCode: '1D1x',
    ringHistory: [],
    inheritedFrom: null,
    comment: null,
    photoUrl: null,
  },
  {
    id: 'p31',
    code: '1D2',
    name: 'Dirk Geppert',
    gender: 'm',
    birthDate: '2003-05-05',
    deathDate: null,
    birthPlace: 'Köln',
    parentId: 'p27',
    partnerId: null,
    hasRing: false,
    ringCode: '1D2',
    ringHistory: [],
    inheritedFrom: null,
    comment: null,
    photoUrl: null,
  },

  // Generation 5
  // Kind von 1A11 (p19)
  {
    id: 'p32',
    code: '1D11',
    name: 'Elias Geppert',
    gender: 'm',
    birthDate: '2024-01-01',
    deathDate: null,
    birthPlace: 'Köln',
    parentId: 'p29', // (Kind von Britta 1D1)
    partnerId: null,
    hasRing: false,
    ringCode: '1D11',
    ringHistory: [],
    inheritedFrom: null,
    comment: null,
    photoUrl: null,
  },

  // Zusatzkinder zur Abrundung 30+
  {
    id: 'p33',
    code: '1A13',
    name: 'Franziska Geppert',
    gender: 'f',
    birthDate: '2022-08-18',
    deathDate: null,
    birthPlace: 'Berlin',
    parentId: 'p9',
    partnerId: null,
    hasRing: false,
    ringCode: '1A13',
    ringHistory: [],
    inheritedFrom: null,
    comment: null,
    photoUrl: null,
  },
  {
    id: 'p34',
    code: '1B12',
    name: 'Gregor Geppert',
    gender: 'm',
    birthDate: '2015-11-26',
    deathDate: null,
    birthPlace: 'Hamburg',
    parentId: 'p13',
    partnerId: null,
    hasRing: false,
    ringCode: '1B12',
    ringHistory: [],
    inheritedFrom: null,
    comment: null,
    photoUrl: null,
  },
];

export default sampleData;
