// sampleData.ts
// Beispiel-Datensatz mit 50 Personen, 6 Generationen

export interface Person {
  id: string;
  ring: string;              // Ring-Code
  vorname: string;
  nachname: string;
  geburtsdatum: string;
  sterbedatum?: string;      // optional
  geschlecht: "m" | "w" | "d";
  eltern?: string[];         // IDs der Eltern
  partner?: string[];        // IDs der Partner
  kinder?: string[];         // IDs der Kinder
}

// Personenliste
export const sampleData: Person[] = [
  // Generation 1 (Urgroßeltern, Ring 1)
  {
    id: "P1",
    ring: "R1",
    vorname: "Karl",
    nachname: "Müller",
    geburtsdatum: "1900-03-12",
    sterbedatum: "1975-08-10",
    geschlecht: "m",
    kinder: ["P5", "P6"],
    partner: ["P2"],
  },
  {
    id: "P2",
    ring: "R1",
    vorname: "Anna",
    nachname: "Schmidt",
    geburtsdatum: "1902-11-04",
    sterbedatum: "1980-06-22",
    geschlecht: "w",
    kinder: ["P5", "P6"],
    partner: ["P1"],
  },
  {
    id: "P3",
    ring: "R1",
    vorname: "Wilhelm",
    nachname: "Koch",
    geburtsdatum: "1898-07-01",
    sterbedatum: "1970-01-30",
    geschlecht: "m",
    kinder: ["P7"],
    partner: ["P4"],
  },
  {
    id: "P4",
    ring: "R1",
    vorname: "Martha",
    nachname: "Lehmann",
    geburtsdatum: "1905-09-18",
    geschlecht: "w",
    kinder: ["P7"],
    partner: ["P3"],
  },

  // Generation 2 (Großeltern, Ring 2)
  {
    id: "P5",
    ring: "R2",
    vorname: "Heinrich",
    nachname: "Müller",
    geburtsdatum: "1925-04-02",
    sterbedatum: "1999-12-01",
    geschlecht: "m",
    eltern: ["P1", "P2"],
    kinder: ["P10", "P11"],
    partner: ["P8"],
  },
  {
    id: "P6",
    ring: "R2",
    vorname: "Elisabeth",
    nachname: "Müller",
    geburtsdatum: "1928-02-14",
    geschlecht: "w",
    eltern: ["P1", "P2"],
    kinder: ["P12"],
    partner: ["P9"],
  },
  {
    id: "P7",
    ring: "R2",
    vorname: "Friedrich",
    nachname: "Koch",
    geburtsdatum: "1930-06-23",
    geschlecht: "m",
    eltern: ["P3", "P4"],
    kinder: ["P13", "P14"],
    partner: ["P20"],
  },
  {
    id: "P8",
    ring: "R2",
    vorname: "Gertrud",
    nachname: "Fischer",
    geburtsdatum: "1927-01-19",
    geschlecht: "w",
    kinder: ["P10", "P11"],
    partner: ["P5"],
  },
  {
    id: "P9",
    ring: "R2",
    vorname: "Josef",
    nachname: "Weber",
    geburtsdatum: "1924-12-05",
    geschlecht: "m",
    kinder: ["P12"],
    partner: ["P6"],
  },
  {
    id: "P20",
    ring: "R2",
    vorname: "Luise",
    nachname: "Klein",
    geburtsdatum: "1931-03-03",
    geschlecht: "w",
    kinder: ["P13", "P14"],
    partner: ["P7"],
  },

  // Generation 3 (Eltern, Ring 3)
  {
    id: "P10",
    ring: "R3",
    vorname: "Dieter",
    nachname: "Müller",
    geburtsdatum: "1950-10-11",
    geschlecht: "m",
    eltern: ["P5", "P8"],
    kinder: ["P21", "P22"],
    partner: ["P15"],
  },
  {
    id: "P11",
    ring: "R3",
    vorname: "Ingrid",
    nachname: "Müller",
    geburtsdatum: "1952-07-16",
    geschlecht: "w",
    eltern: ["P5", "P8"],
    kinder: ["P23"],
    partner: ["P16"],
  },
  {
    id: "P12",
    ring: "R3",
    vorname: "Rudolf",
    nachname: "Weber",
    geburtsdatum: "1955-01-07",
    geschlecht: "m",
    eltern: ["P6", "P9"],
    kinder: ["P24"],
    partner: ["P17"],
  },
  {
    id: "P13",
    ring: "R3",
    vorname: "Monika",
    nachname: "Koch",
    geburtsdatum: "1953-08-08",
    geschlecht: "w",
    eltern: ["P7", "P20"],
    kinder: ["P25", "P26"],
    partner: ["P18"],
  },
  {
    id: "P14",
    ring: "R3",
    vorname: "Herbert",
    nachname: "Koch",
    geburtsdatum: "1957-12-12",
    geschlecht: "m",
    eltern: ["P7", "P20"],
    kinder: ["P27"],
    partner: ["P19"],
  },
  {
    id: "P15",
    ring: "R3",
    vorname: "Christa",
    nachname: "Neumann",
    geburtsdatum: "1951-05-19",
    geschlecht: "w",
    kinder: ["P21", "P22"],
    partner: ["P10"],
  },
  {
    id: "P16",
    ring: "R3",
    vorname: "Hans",
    nachname: "Richter",
    geburtsdatum: "1950-09-25",
    geschlecht: "m",
    kinder: ["P23"],
    partner: ["P11"],
  },
  {
    id: "P17",
    ring: "R3",
    vorname: "Sabine",
    nachname: "Bauer",
    geburtsdatum: "1956-04-21",
    geschlecht: "w",
    kinder: ["P24"],
    partner: ["P12"],
  },
  {
    id: "P18",
    ring: "R3",
    vorname: "Peter",
    nachname: "Scholz",
    geburtsdatum: "1952-06-10",
    geschlecht: "m",
    kinder: ["P25", "P26"],
    partner: ["P13"],
  },
  {
    id: "P19",
    ring: "R3",
    vorname: "Gisela",
    nachname: "Wolf",
    geburtsdatum: "1959-11-29",
    geschlecht: "w",
    kinder: ["P27"],
    partner: ["P14"],
  },

  // Generation 4 (Ring 4)
  {
    id: "P21",
    ring: "R4",
    vorname: "Thomas",
    nachname: "Müller",
    geburtsdatum: "1975-03-01",
    geschlecht: "m",
    eltern: ["P10", "P15"],
    kinder: ["P30"],
    partner: ["P28"],
  },
  {
    id: "P22",
    ring: "R4",
    vorname: "Claudia",
    nachname: "Müller",
    geburtsdatum: "1977-09-14",
    geschlecht: "w",
    eltern: ["P10", "P15"],
    kinder: ["P31"],
    partner: ["P29"],
  },
  {
    id: "P23",
    ring: "R4",
    vorname: "Michael",
    nachname: "Richter",
    geburtsdatum: "1979-12-24",
    geschlecht: "m",
    eltern: ["P11", "P16"],
    kinder: ["P32"],
    partner: ["P33"],
  },
  {
    id: "P24",
    ring: "R4",
    vorname: "Katrin",
    nachname: "Weber",
    geburtsdatum: "1980-02-20",
    geschlecht: "w",
    eltern: ["P12", "P17"],
    kinder: ["P34"],
    partner: ["P35"],
  },
  {
    id: "P25",
    ring: "R4",
    vorname: "Stefan",
    nachname: "Scholz",
    geburtsdatum: "1974-04-07",
    geschlecht: "m",
    eltern: ["P13", "P18"],
    kinder: ["P36"],
    partner: ["P37"],
  },
  {
    id: "P26",
    ring: "R4",
    vorname: "Andrea",
    nachname: "Scholz",
    geburtsdatum: "1976-06-17",
    geschlecht: "w",
    eltern: ["P13", "P18"],
    kinder: ["P38"],
    partner: ["P39"],
  },
  {
    id: "P27",
    ring: "R4",
    vorname: "Markus",
    nachname: "Koch",
    geburtsdatum: "1982-08-22",
    geschlecht: "m",
    eltern: ["P14", "P19"],
    kinder: ["P40"],
    partner: ["P41"],
  },

  // Generation 5 (Ring 5)
  {
    id: "P28",
    ring: "R5",
    vorname: "Julia",
    nachname: "Becker",
    geburtsdatum: "1978-07-03",
    geschlecht: "w",
    kinder: ["P30"],
    partner: ["P21"],
  },
  {
    id: "P29",
    ring: "R5",
    vorname: "Jürgen",
    nachname: "Hoffmann",
    geburtsdatum: "1975-02-11",
    geschlecht: "m",
    kinder: ["P31"],
    partner: ["P22"],
  },
  {
    id: "P30",
    ring: "R5",
    vorname: "Nina",
    nachname: "Müller",
    geburtsdatum: "2000-01-01",
    geschlecht: "w",
    eltern: ["P21", "P28"],
  },
  {
    id: "P31",
    ring: "R5",
    vorname: "Sebastian",
    nachname: "Hoffmann",
    geburtsdatum: "2002-02-02",
    geschlecht: "m",
    eltern: ["P22", "P29"],
  },
  {
    id: "P32",
    ring: "R5",
    vorname: "Lea",
    nachname: "Richter",
    geburtsdatum: "2003-03-03",
    geschlecht: "w",
    eltern: ["P23", "P33"],
  },
  {
    id: "P33",
    ring: "R5",
    vorname: "Holger",
    nachname: "Maier",
    geburtsdatum: "1979-05-05",
    geschlecht: "m",
    kinder: ["P32"],
    partner: ["P23"],
  },
  {
    id: "P34",
    ring: "R5",
    vorname: "Lukas",
    nachname: "Weber",
    geburtsdatum: "2005-04-04",
    geschlecht: "m",
    eltern: ["P24", "P35"],
  },
  {
    id: "P35",
    ring: "R5",
    vorname: "Birgit",
    nachname: "Schäfer",
    geburtsdatum: "1981-09-09",
    geschlecht: "w",
    kinder: ["P34"],
    partner: ["P24"],
  },
  {
    id: "P36",
    ring: "R5",
    vorname: "Sven",
    nachname: "Scholz",
    geburtsdatum: "2006-06-06",
    geschlecht: "m",
    eltern: ["P25", "P37"],
  },
  {
    id: "P37",
    ring: "R5",
    vorname: "Heike",
    nachname: "Krüger",
    geburtsdatum: "1975-07-07",
    geschlecht: "w",
    kinder: ["P36"],
    partner: ["P25"],
  },
  {
    id: "P38",
    ring: "R5",
    vorname: "Paul",
    nachname: "Scholz",
    geburtsdatum: "2007-08-08",
    geschlecht: "m",
    eltern: ["P26", "P39"],
  },
  {
    id: "P39",
    ring: "R5",
    vorname: "Simone",
    nachname: "Wagner",
    geburtsdatum: "1978-09-09",
    geschlecht: "w",
    kinder: ["P38"],
    partner: ["P26"],
  },
  {
    id: "P40",
    ring: "R5",
    vorname: "Daniel",
    nachname: "Koch",
    geburtsdatum: "2010-10-10",
    geschlecht: "d", // divers
    eltern: ["P27", "P41"],
  },
  {
    id: "P41",
    ring: "R5",
    vorname: "Anja",
    nachname: "Lorenz",
    geburtsdatum: "1983-11-11",
    geschlecht: "w",
    kinder: ["P40"],
    partner: ["P27"],
  },

  // Generation 6 (Ring 6, jüngste Generation)
  {
    id: "P42",
    ring: "R6",
    vorname: "Mia",
    nachname: "Müller",
    geburtsdatum: "2020-01-15",
    geschlecht: "w",
    eltern: ["P30"],
  },
  {
    id: "P43",
    ring: "R6",
    vorname: "Jonas",
    nachname: "Hoffmann",
    geburtsdatum: "2021-02-20",
    geschlecht: "m",
    eltern: ["P31"],
  },
  {
    id: "P44",
    ring: "R6",
    vorname: "Emma",
    nachname: "Richter",
    geburtsdatum: "2019-03-25",
    geschlecht: "w",
    eltern: ["P32"],
  },
  {
    id: "P45",
    ring: "R6",
    vorname: "Finn",
    nachname: "Weber",
    geburtsdatum: "2022-04-30",
    geschlecht: "m",
    eltern: ["P34"],
  },
  {
    id: "P46",
    ring: "R6",
    vorname: "Sophie",
    nachname: "Scholz",
    geburtsdatum: "2023-05-05",
    geschlecht: "w",
    eltern: ["P36"],
  },
  {
    id: "P47",
    ring: "R6",
    vorname: "Noah",
    nachname: "Scholz",
    geburtsdatum: "2024-06-10",
    geschlecht: "m",
    eltern: ["P38"],
  },
  {
    id: "P48",
    ring: "R6",
    vorname: "Lara",
    nachname: "Koch",
    geburtsdatum: "2021-07-20",
    geschlecht: "w",
    eltern: ["P40"],
  },

  // Zwei Personen ohne Partner/Kinder (Sonderfall)
  {
    id: "P49",
    ring: "R4",
    vorname: "Eva",
    nachname: "Müller",
    geburtsdatum: "1985-08-15",
    geschlecht: "w",
    eltern: ["P6", "P9"], // Tochter von Elisabeth & Josef
  },
  {
    id: "P50",
    ring: "R5",
    vorname: "Oliver",
    nachname: "Richter",
    geburtsdatum: "2001-09-12",
    geschlecht: "m",
    eltern: ["P11", "P16"],
  },
];
