// src/services/sampleData.ts
import type { Person } from '../types';

export const samplePeople: Person[] = [
  {
    id: 'p001',
    name: 'Karl Geppert',
    code: '1A1001',
    ringCode: '1A1001',
    parentId: null,
    partnerId: 'p002',
    gender: 'm',
    hasRing: true,
    birthDate: '1930-04-15',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Stammvater der Familie.',
  },
  {
    id: 'p002',
    name: 'Anna Müller-Geppert',
    code: '1A1002',
    ringCode: null,
    parentId: null,
    partnerId: 'p001',
    gender: 'w',
    hasRing: false,
    birthDate: '1932-06-20',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Stamm-Mutter; geb. Müller.',
  },
  {
    id: 'p003',
    name: 'Hans Geppert',
    code: '1B1003',
    ringCode: '1A1001→1B1003',
    parentId: 'p001',
    partnerId: 'p004',
    gender: 'm',
    hasRing: true,
    birthDate: '1955-02-12',
    birthPlace: 'Berlin',
    deathDate: '2020-03-15',
    photoUrl: null,
    inheritedFrom: 'p001',
    comment: 'Erster Sohn von Karl, Ring geerbt.',
  },
  {
    id: 'p004',
    name: 'Maria Schulze-Geppert',
    code: '1B1004',
    ringCode: null,
    parentId: null,
    partnerId: 'p003',
    gender: 'w',
    hasRing: false,
    birthDate: '1956-09-10',
    birthPlace: 'Hamburg',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Ehefrau von Hans.',
  },
  {
    id: 'p005',
    name: 'Peter Geppert',
    code: '1B1005',
    ringCode: null,
    parentId: 'p001',
    partnerId: 'p006',
    gender: 'm',
    hasRing: false,
    birthDate: '1958-07-01',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Zweiter Sohn von Karl.',
  },
  {
    id: 'p006',
    name: 'Sabine Krüger-Geppert',
    code: '1B1006',
    ringCode: null,
    parentId: null,
    partnerId: 'p005',
    gender: 'w',
    hasRing: false,
    birthDate: '1960-01-22',
    birthPlace: 'Köln',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Ehefrau von Peter.',
  },
  {
    id: 'p007',
    name: 'Claudia Geppert',
    code: '1C1007',
    ringCode: '1B1003→1C1007',
    parentId: 'p003',
    partnerId: 'p008',
    gender: 'w',
    hasRing: true,
    birthDate: '1980-05-14',
    birthPlace: 'München',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: 'p003',
    comment: 'Tochter von Hans; Ring übernommen.',
  },
  {
    id: 'p008',
    name: 'Markus Schneider-Geppert',
    code: '1C1008',
    ringCode: null,
    parentId: null,
    partnerId: 'p007',
    gender: 'm',
    hasRing: false,
    birthDate: '1979-11-03',
    birthPlace: 'Stuttgart',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Ehemann von Claudia.',
  },
  {
    id: 'p009',
    name: 'Thomas Geppert',
    code: '1C1009',
    ringCode: '1B1005→1C1009',
    parentId: 'p005',
    partnerId: 'p010',
    gender: 'm',
    hasRing: true,
    birthDate: '1985-03-02',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: 'p005',
    comment: 'Sohn von Peter; erbte Ring nach Vaters Tod.',
  },
  {
    id: 'p010',
    name: 'Julia Weber-Geppert',
    code: '1C1010',
    ringCode: null,
    parentId: null,
    partnerId: 'p009',
    gender: 'w',
    hasRing: false,
    birthDate: '1987-12-05',
    birthPlace: 'Leipzig',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Ehefrau von Thomas.',
  },
    {
    id: 'p011',
    name: 'Lena Geppert',
    code: '1C1011',
    ringCode: null,
    parentId: 'p005',
    partnerId: 'p012',
    gender: 'w',
    hasRing: false,
    birthDate: '1988-08-21',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Tochter von Peter.',
  },
  {
    id: 'p012',
    name: 'Andreas Hoffmann',
    code: '1C1012',
    ringCode: null,
    parentId: null,
    partnerId: 'p011',
    gender: 'm',
    hasRing: false,
    birthDate: '1985-10-18',
    birthPlace: 'Hamburg',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Ehemann von Lena.',
  },
  {
    id: 'p013',
    name: 'Michael Geppert',
    code: '1D1013',
    ringCode: '1C1009→1D1013',
    parentId: 'p009',
    partnerId: 'p014',
    gender: 'm',
    hasRing: true,
    birthDate: '2010-01-11',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: 'p009',
    comment: 'Sohn von Thomas; Ring übernommen.',
  },
  {
    id: 'p014',
    name: 'Sophie Lehmann-Geppert',
    code: '1D1014',
    ringCode: null,
    parentId: null,
    partnerId: 'p013',
    gender: 'w',
    hasRing: false,
    birthDate: '2012-02-14',
    birthPlace: 'München',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Ehefrau von Michael.',
  },
  {
    id: 'p015',
    name: 'Sarah Geppert',
    code: '1D1015',
    ringCode: null,
    parentId: 'p009',
    partnerId: null,
    gender: 'w',
    hasRing: false,
    birthDate: '2012-09-19',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Tochter von Thomas; hat keinen Partner.',
  },
  {
    id: 'p016',
    name: 'Jonas Geppert',
    code: '1D1016',
    ringCode: null,
    parentId: 'p011',
    partnerId: null,
    gender: 'm',
    hasRing: false,
    birthDate: '2015-05-05',
    birthPlace: 'Hamburg',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Sohn von Lena; ohne Ring.',
  },
  {
    id: 'p017',
    name: 'Paul Geppert',
    code: '1E1017',
    ringCode: '1D1013→1E1017',
    parentId: 'p013',
    partnerId: null,
    gender: 'm',
    hasRing: true,
    birthDate: '2035-07-07',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: 'p013',
    comment: 'Enkel mit geerbtem Ring.',
  },
  {
    id: 'p018',
    name: 'Nina Geppert',
    code: '1E1018',
    ringCode: null,
    parentId: 'p013',
    partnerId: null,
    gender: 'w',
    hasRing: false,
    birthDate: '2038-11-11',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Enkelin ohne Ring.',
  },
  {
    id: 'p019',
    name: 'David Geppert',
    code: '1C1019',
    ringCode: null,
    parentId: 'p005',
    partnerId: 'p020',
    gender: 'm',
    hasRing: false,
    birthDate: '1990-12-12',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Sohn von Peter.',
  },
  {
    id: 'p020',
    name: 'Laura Klein-Geppert',
    code: '1C1020',
    ringCode: null,
    parentId: null,
    partnerId: 'p019',
    gender: 'w',
    hasRing: false,
    birthDate: '1991-03-30',
    birthPlace: 'Dresden',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Ehefrau von David.',
  },
  {
    id: 'p021',
    name: 'Oliver Geppert',
    code: '1D1021',
    ringCode: '1C1019→1D1021',
    parentId: 'p019',
    partnerId: null,
    gender: 'm',
    hasRing: true,
    birthDate: '2018-04-04',
    birthPlace: 'Leipzig',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: 'p019',
    comment: 'Kind von David mit geerbtem Ring.',
  },
  {
    id: 'p022',
    name: 'Katharina Geppert',
    code: '1D1022',
    ringCode: null,
    parentId: 'p019',
    partnerId: null,
    gender: 'w',
    hasRing: false,
    birthDate: '2020-06-06',
    birthPlace: 'Leipzig',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Tochter von David.',
  },
    {
    id: 'p023',
    name: 'Matthias Geppert',
    code: '1C1023',
    ringCode: null,
    parentId: 'p007',
    partnerId: 'p024',
    gender: 'm',
    hasRing: false,
    birthDate: '1983-09-09',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Sohn von Anna.',
  },
  {
    id: 'p024',
    name: 'Elena Fischer-Geppert',
    code: '1C1024',
    ringCode: null,
    parentId: null,
    partnerId: 'p023',
    gender: 'w',
    hasRing: false,
    birthDate: '1986-12-01',
    birthPlace: 'Köln',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Partnerin von Matthias.',
  },
  {
    id: 'p025',
    name: 'Julia Geppert',
    code: '1D1025',
    ringCode: '1C1023→1D1025',
    parentId: 'p023',
    partnerId: null,
    gender: 'w',
    hasRing: true,
    birthDate: '2012-02-02',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: 'p023',
    comment: 'Tochter mit Ring.',
  },
  {
    id: 'p026',
    name: 'Tim Geppert',
    code: '1D1026',
    ringCode: null,
    parentId: 'p023',
    partnerId: null,
    gender: 'm',
    hasRing: false,
    birthDate: '2015-10-10',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Sohn von Matthias.',
  },
  {
    id: 'p027',
    name: 'Eva Geppert',
    code: '1C1027',
    ringCode: null,
    parentId: 'p007',
    partnerId: 'p028',
    gender: 'w',
    hasRing: false,
    birthDate: '1985-03-03',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Zweite Tochter von Anna.',
  },
  {
    id: 'p028',
    name: 'Mark Weber',
    code: '1C1028',
    ringCode: null,
    parentId: null,
    partnerId: 'p027',
    gender: 'm',
    hasRing: false,
    birthDate: '1984-07-07',
    birthPlace: 'Hannover',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Partner von Eva.',
  },
  {
    id: 'p029',
    name: 'Felix Geppert',
    code: '1D1029',
    ringCode: '1C1027→1D1029',
    parentId: 'p027',
    partnerId: null,
    gender: 'm',
    hasRing: true,
    birthDate: '2016-09-09',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: 'p027',
    comment: 'Sohn mit Ring.',
  },
  {
    id: 'p030',
    name: 'Marie Geppert',
    code: '1D1030',
    ringCode: null,
    parentId: 'p027',
    partnerId: null,
    gender: 'w',
    hasRing: false,
    birthDate: '2019-01-01',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Tochter ohne Ring.',
  },
  {
    id: 'p031',
    name: 'Klara Geppert',
    code: '1C1031',
    ringCode: null,
    parentId: 'p007',
    partnerId: 'p032',
    gender: 'w',
    hasRing: false,
    birthDate: '1987-11-11',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Dritte Tochter von Anna.',
  },
  {
    id: 'p032',
    name: 'Sebastian Koch',
    code: '1C1032',
    ringCode: null,
    parentId: null,
    partnerId: 'p031',
    gender: 'm',
    hasRing: false,
    birthDate: '1986-05-05',
    birthPlace: 'Frankfurt',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Partner von Klara.',
  },
  {
    id: 'p033',
    name: 'Lukas Geppert',
    code: '1D1033',
    ringCode: '1C1031→1D1033',
    parentId: 'p031',
    partnerId: null,
    gender: 'm',
    hasRing: true,
    birthDate: '2020-04-04',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: 'p031',
    comment: 'Sohn mit Ring.',
  },
  {
    id: 'p034',
    name: 'Hannah Geppert',
    code: '1D1034',
    ringCode: null,
    parentId: 'p031',
    partnerId: null,
    gender: 'w',
    hasRing: false,
    birthDate: '2022-06-06',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: null,
    comment: 'Tochter ohne Ring.',
  },
  {
    id: 'p035',
    name: 'Samuel Geppert',
    code: '1E1035',
    ringCode: '1D1033→1E1035',
    parentId: 'p033',
    partnerId: null,
    gender: 'm',
    hasRing: true,
    birthDate: '2045-08-08',
    birthPlace: 'Berlin',
    deathDate: null,
    photoUrl: null,
    inheritedFrom: 'p033',
    comment: 'Enkel mit Ring, letzte Generation.',
  },
];

export const samplePeople: Person[] = sampleData;
